# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Master.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import Add_Slave
import Get_Data

from Add_Slave import Modbus_Slaves , Ui_Add_Slave
from Get_Data import Ui_MainWindow
class Ui_ModbusMASTER(object):

    global Modbus_Slaves

    def setupUi(self, ModbusMASTER):
        ModbusMASTER.setObjectName("ModbusMASTER")
        ModbusMASTER.resize(582, 288)
        self.centralwidget = QtWidgets.QWidget(ModbusMASTER)
        self.centralwidget.setObjectName("centralwidget")
        
        self.BUT_ADD = QtWidgets.QPushButton(self.centralwidget)
        self.BUT_ADD.setGeometry(QtCore.QRect(10, 110, 271, 51))
        self.BUT_ADD.setObjectName("BUT_ADD")
        self.BUT_ADD.clicked.connect(self.Add_Slave_CALLBACK)
        
        self.Intro_Label = QtWidgets.QLabel(self.centralwidget)
        self.Intro_Label.setGeometry(QtCore.QRect(140, 30, 271, 51))
        self.Intro_Label.setObjectName("Intro_Label")
        
        self.BUT_GET = QtWidgets.QPushButton(self.centralwidget)
        self.BUT_GET.setGeometry(QtCore.QRect(290, 110, 271, 51))
        self.BUT_GET.setObjectName("BUT_GET")
        self.BUT_GET.clicked.connect(self.Get_Data_CALLBACK)
        
        
        ModbusMASTER.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ModbusMASTER)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 582, 26))
        self.menubar.setObjectName("menubar")
        ModbusMASTER.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ModbusMASTER)
        self.statusbar.setObjectName("statusbar")
        ModbusMASTER.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(ModbusMASTER)
        self.toolBar.setObjectName("toolBar")
        ModbusMASTER.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)

        self.retranslateUi(ModbusMASTER)
        QtCore.QMetaObject.connectSlotsByName(ModbusMASTER)

    def retranslateUi(self, ModbusMASTER):
        _translate = QtCore.QCoreApplication.translate
        ModbusMASTER.setWindowTitle(_translate("ModbusMASTER", "MainWindow"))
        self.BUT_ADD.setText(_translate("ModbusMASTER", "Add a modbus Slave"))
        self.Intro_Label.setText(_translate("ModbusMASTER", "Modbus Master ready to connect"))
        self.BUT_GET.setText(_translate("ModbusMASTER", "Get Data from a slave"))
        self.toolBar.setWindowTitle(_translate("ModbusMASTER", "toolBar"))
    
    def Get_Data_CALLBACK (self) :
        self.GET_WIN = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self.GET_WIN)
        self.ui.Insert_Items(Modbus_Slaves)
        self.GET_WIN.show() 
        
    
    def Add_Slave_CALLBACK (self) :
        self.Add = QtWidgets.QMainWindow()
        self.ui = Ui_Add_Slave()
        self.ui.setupUi(self.Add)
        self.Add.show()
        
        
        




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ModbusMASTER = QtWidgets.QMainWindow()
    ui = Ui_ModbusMASTER()
    ui.setupUi(ModbusMASTER)
    ModbusMASTER.show()
    sys.exit(app.exec_())
